// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: oracle_user_contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.OracleUser {

  #region Events
  public partial class QueryDataRecorded : aelf::IEvent<QueryDataRecorded>
  {
    public global::System.Collections.Generic.IEnumerable<QueryDataRecorded> GetIndexed()
    {
      return new List<QueryDataRecorded>
      {
      };
    }

    public QueryDataRecorded GetNonIndexed()
    {
      return new QueryDataRecorded
      {
        Data = Data,
        Timestamp = Timestamp,
      };
    }
  }

  #endregion
  public static partial class OracleUserContractContainer
  {
    static readonly string __ServiceName = "OracleUserContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::AElf.Contracts.OracleUser.QueryTemperatureInput> __Marshaller_QueryTemperatureInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.OracleUser.QueryTemperatureInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Hash> __Marshaller_aelf_Hash = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Hash.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::CallbackInput> __Marshaller_CallbackInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CallbackInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.OracleUser.TemperatureRecordList> __Marshaller_TemperatureRecordList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.OracleUser.TemperatureRecordList.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::AElf.Contracts.OracleUser.QueryTemperatureInput, global::AElf.Types.Hash> __Method_QueryTemperature = new aelf::Method<global::AElf.Contracts.OracleUser.QueryTemperatureInput, global::AElf.Types.Hash>(
        aelf::MethodType.Action,
        __ServiceName,
        "QueryTemperature",
        __Marshaller_QueryTemperatureInput,
        __Marshaller_aelf_Hash);

    static readonly aelf::Method<global::CallbackInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RecordTemperature = new aelf::Method<global::CallbackInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RecordTemperature",
        __Marshaller_CallbackInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.OracleUser.TemperatureRecordList> __Method_GetHistoryTemperatures = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.OracleUser.TemperatureRecordList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetHistoryTemperatures",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_TemperatureRecordList);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AElf.Contracts.OracleUser.OracleUserContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Contracts.OracleUser.OracleUserContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion
  }
}
#endregion

