// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: acs1.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Standards.ACS1 {

    #region Events
    public partial class MethodFeeSet : aelf::IEvent<MethodFeeSet>
    {
        public global::System.Collections.Generic.IEnumerable<MethodFeeSet> GetIndexed()
        {
            return new List<MethodFeeSet>
            {
            };
        }

        public MethodFeeSet GetNonIndexed()
        {
            return new MethodFeeSet
            {
                Method = Method,
                Symbol = Symbol,
                OldFee = OldFee,
                NewFee = NewFee,
            };
        }
    }

    #endregion
}
#endregion