// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: lottery_contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.Lottery {

  #region Events
  public partial class DrewFinished : aelf::IEvent<DrewFinished>
  {
    public global::System.Collections.Generic.IEnumerable<DrewFinished> GetIndexed()
    {
      return new List<DrewFinished>
      {
      };
    }

    public DrewFinished GetNonIndexed()
    {
      return new DrewFinished
      {
        PeriodId = PeriodId,
      };
    }
  }

  public partial class DrewUnfinished : aelf::IEvent<DrewUnfinished>
  {
    public global::System.Collections.Generic.IEnumerable<DrewUnfinished> GetIndexed()
    {
      return new List<DrewUnfinished>
      {
      };
    }

    public DrewUnfinished GetNonIndexed()
    {
      return new DrewUnfinished
      {
        PeriodId = PeriodId,
        ToAwardId = ToAwardId,
      };
    }
  }

  public partial class Staked : aelf::IEvent<Staked>
  {
    public global::System.Collections.Generic.IEnumerable<Staked> GetIndexed()
    {
      return new List<Staked>
      {
      };
    }

    public Staked GetNonIndexed()
    {
      return new Staked
      {
        User = User,
        Amount = Amount,
        LotteryCodeList = LotteryCodeList,
      };
    }
  }

  public partial class Redeemed : aelf::IEvent<Redeemed>
  {
    public global::System.Collections.Generic.IEnumerable<Redeemed> GetIndexed()
    {
      return new List<Redeemed>
      {
      };
    }

    public Redeemed GetNonIndexed()
    {
      return new Redeemed
      {
        User = User,
        Amount = Amount,
        PeriodId = PeriodId,
      };
    }
  }

  public partial class Claimed : aelf::IEvent<Claimed>
  {
    public global::System.Collections.Generic.IEnumerable<Claimed> GetIndexed()
    {
      return new List<Claimed>
      {
      };
    }

    public Claimed GetNonIndexed()
    {
      return new Claimed
      {
        User = User,
        Amount = Amount,
        PeriodId = PeriodId,
        ClaimedLotteryCodeList = ClaimedLotteryCodeList,
      };
    }
  }

  #endregion
  /// <summary>
  /// Only for the activity after eth2aelf ELF token swap.
  /// </summary>
  public static partial class LotteryContractContainer
  {
    static readonly string __ServiceName = "LotteryContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::AElf.Contracts.Lottery.InitializeInput> __Marshaller_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Lottery.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Lottery.DrawInput> __Marshaller_DrawInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Lottery.DrawInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Lottery.OwnLottery> __Marshaller_OwnLottery = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Lottery.OwnLottery.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Lottery.Int64List> __Marshaller_Int64List = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Lottery.Int64List.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Lottery.AwardList> __Marshaller_AwardList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Lottery.AwardList.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Lottery.GetAwardListInput> __Marshaller_GetAwardListInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Lottery.GetAwardListInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Lottery.Lottery> __Marshaller_Lottery = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Lottery.Lottery.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Lottery.Award> __Marshaller_Award = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Lottery.Award.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Lottery.PeriodAward> __Marshaller_PeriodAward = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Lottery.PeriodAward.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Timestamp> __Marshaller_google_protobuf_Timestamp = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Timestamp.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Lottery.AwardAmountMap> __Marshaller_AwardAmountMap = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Lottery.AwardAmountMap.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::AElf.Contracts.Lottery.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::AElf.Contracts.Lottery.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Lottery.DrawInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Draw = new aelf::Method<global::AElf.Contracts.Lottery.DrawInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Draw",
        __Marshaller_DrawInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Lottery.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ResetTimestamp = new aelf::Method<global::AElf.Contracts.Lottery.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ResetTimestamp",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AElf.Contracts.Lottery.OwnLottery> __Method_Stake = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AElf.Contracts.Lottery.OwnLottery>(
        aelf::MethodType.Action,
        __ServiceName,
        "Stake",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_OwnLottery);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Redeem = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Redeem",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Claim = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Claim",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetCurrentPeriodId = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCurrentPeriodId",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetTotalLotteryCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTotalLotteryCount",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetTotalAwardCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTotalAwardCount",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.Lottery.Int64List> __Method_GetLotteryCodeListByUserAddress = new aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.Lottery.Int64List>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLotteryCodeListByUserAddress",
        __Marshaller_aelf_Address,
        __Marshaller_Int64List);

    static readonly aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.Lottery.AwardList> __Method_GetAwardListByUserAddress = new aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.Lottery.AwardList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAwardListByUserAddress",
        __Marshaller_aelf_Address,
        __Marshaller_AwardList);

    static readonly aelf::Method<global::AElf.Contracts.Lottery.GetAwardListInput, global::AElf.Contracts.Lottery.AwardList> __Method_GetAwardList = new aelf::Method<global::AElf.Contracts.Lottery.GetAwardListInput, global::AElf.Contracts.Lottery.AwardList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAwardList",
        __Marshaller_GetAwardListInput,
        __Marshaller_AwardList);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AElf.Contracts.Lottery.Lottery> __Method_GetLottery = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AElf.Contracts.Lottery.Lottery>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLottery",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_Lottery);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetStakingAmount = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetStakingAmount",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.Lottery.OwnLottery> __Method_GetOwnLottery = new aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.Lottery.OwnLottery>(
        aelf::MethodType.View,
        __ServiceName,
        "GetOwnLottery",
        __Marshaller_aelf_Address,
        __Marshaller_OwnLottery);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AElf.Contracts.Lottery.Award> __Method_GetAward = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AElf.Contracts.Lottery.Award>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAward",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_Award);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AElf.Contracts.Lottery.PeriodAward> __Method_GetPeriodAward = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AElf.Contracts.Lottery.PeriodAward>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPeriodAward",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_PeriodAward);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Timestamp> __Method_GetStartTimestamp = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Timestamp>(
        aelf::MethodType.View,
        __ServiceName,
        "GetStartTimestamp",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Timestamp);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Timestamp> __Method_GetShutdownTimestamp = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Timestamp>(
        aelf::MethodType.View,
        __ServiceName,
        "GetShutdownTimestamp",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Timestamp);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Timestamp> __Method_GetRedeemTimestamp = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Timestamp>(
        aelf::MethodType.View,
        __ServiceName,
        "GetRedeemTimestamp",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Timestamp);

    static readonly aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.Lottery.AwardAmountMap> __Method_GetAwardAmountMap = new aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.Lottery.AwardAmountMap>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAwardAmountMap",
        __Marshaller_aelf_Address,
        __Marshaller_AwardAmountMap);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AElf.Contracts.Lottery.LotteryContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Contracts.Lottery.LotteryContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion
  }
}
#endregion

