// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: merkle_tree_generator.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.MerkleTreeGeneratorContract {

  #region Events
  internal partial class ReceiptMakerRegistered : aelf::IEvent<ReceiptMakerRegistered>
  {
    public global::System.Collections.Generic.IEnumerable<ReceiptMakerRegistered> GetIndexed()
    {
      return new List<ReceiptMakerRegistered>
      {
      new ReceiptMakerRegistered
      {
        ReceiptMakerAddress = ReceiptMakerAddress
      },
      };
    }

    public ReceiptMakerRegistered GetNonIndexed()
    {
      return new ReceiptMakerRegistered
      {
      };
    }
  }

  internal partial class ReceiptMakerUnRegistered : aelf::IEvent<ReceiptMakerUnRegistered>
  {
    public global::System.Collections.Generic.IEnumerable<ReceiptMakerUnRegistered> GetIndexed()
    {
      return new List<ReceiptMakerUnRegistered>
      {
      new ReceiptMakerUnRegistered
      {
        ReceiptMakerAddress = ReceiptMakerAddress
      },
      };
    }

    public ReceiptMakerUnRegistered GetNonIndexed()
    {
      return new ReceiptMakerUnRegistered
      {
      };
    }
  }

  #endregion
  internal static partial class MerkleTreeGeneratorContractContainer
  {
    static readonly string __ServiceName = "MerkleTreeGeneratorContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::AElf.Contracts.MerkleTreeGeneratorContract.InitializeInput> __Marshaller_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MerkleTreeGeneratorContract.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MerkleTreeGeneratorContract.RegisterReceiptMakerInput> __Marshaller_RegisterReceiptMakerInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MerkleTreeGeneratorContract.RegisterReceiptMakerInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerkleTreeInput> __Marshaller_GetMerkleTreeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerkleTreeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerkleTreeOutput> __Marshaller_GetMerkleTreeOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerkleTreeOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MerkleTreeGeneratorContract.GetReceiptMakerOutput> __Marshaller_GetReceiptMakerOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MerkleTreeGeneratorContract.GetReceiptMakerOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerklePathInput> __Marshaller_GetMerklePathInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerklePathInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.MerklePath> __Marshaller_aelf_MerklePath = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.MerklePath.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::AElf.Contracts.MerkleTreeGeneratorContract.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::AElf.Contracts.MerkleTreeGeneratorContract.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.MerkleTreeGeneratorContract.RegisterReceiptMakerInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RegisterReceiptMaker = new aelf::Method<global::AElf.Contracts.MerkleTreeGeneratorContract.RegisterReceiptMakerInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RegisterReceiptMaker",
        __Marshaller_RegisterReceiptMakerInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UnRegisterReceiptMaker = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UnRegisterReceiptMaker",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetFullTreeCount = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetFullTreeCount",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerkleTreeInput, global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerkleTreeOutput> __Method_GetMerkleTree = new aelf::Method<global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerkleTreeInput, global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerkleTreeOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMerkleTree",
        __Marshaller_GetMerkleTreeInput,
        __Marshaller_GetMerkleTreeOutput);

    static readonly aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.MerkleTreeGeneratorContract.GetReceiptMakerOutput> __Method_GetReceiptMaker = new aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.MerkleTreeGeneratorContract.GetReceiptMakerOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetReceiptMaker",
        __Marshaller_aelf_Address,
        __Marshaller_GetReceiptMakerOutput);

    static readonly aelf::Method<global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerklePathInput, global::AElf.Types.MerklePath> __Method_GetMerklePath = new aelf::Method<global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerklePathInput, global::AElf.Types.MerklePath>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMerklePath",
        __Marshaller_GetMerklePathInput,
        __Marshaller_aelf_MerklePath);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AElf.Contracts.MerkleTreeGeneratorContract.MerkleTreeGeneratorReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Contracts.MerkleTreeGeneratorContract.MerkleTreeGeneratorReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

    public class MerkleTreeGeneratorContractReferenceState : global::AElf.Sdk.CSharp.State.ContractReferenceState
    {
      internal global::AElf.Sdk.CSharp.State.MethodReference<global::AElf.Contracts.MerkleTreeGeneratorContract.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> Initialize { get; set; }
      internal global::AElf.Sdk.CSharp.State.MethodReference<global::AElf.Contracts.MerkleTreeGeneratorContract.RegisterReceiptMakerInput, global::Google.Protobuf.WellKnownTypes.Empty> RegisterReceiptMaker { get; set; }
      internal global::AElf.Sdk.CSharp.State.MethodReference<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> UnRegisterReceiptMaker { get; set; }
      internal global::AElf.Sdk.CSharp.State.MethodReference<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> GetFullTreeCount { get; set; }
      internal global::AElf.Sdk.CSharp.State.MethodReference<global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerkleTreeInput, global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerkleTreeOutput> GetMerkleTree { get; set; }
      internal global::AElf.Sdk.CSharp.State.MethodReference<global::AElf.Types.Address, global::AElf.Contracts.MerkleTreeGeneratorContract.GetReceiptMakerOutput> GetReceiptMaker { get; set; }
      internal global::AElf.Sdk.CSharp.State.MethodReference<global::AElf.Contracts.MerkleTreeGeneratorContract.GetMerklePathInput, global::AElf.Types.MerklePath> GetMerklePath { get; set; }
    }
  }
}
#endregion

