// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: merkle_tree_recorder.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace MTRecorder {

  #region Events
  public partial class RecorderCreated : aelf::IEvent<RecorderCreated>
  {
    public global::System.Collections.Generic.IEnumerable<RecorderCreated> GetIndexed()
    {
      return new List<RecorderCreated>
      {
      };
    }

    public RecorderCreated GetNonIndexed()
    {
      return new RecorderCreated
      {
        Admin = Admin,
        MaximalLeafCount = MaximalLeafCount,
        RecorderId = RecorderId,
      };
    }
  }

  public partial class MerkleTreeRecorded : aelf::IEvent<MerkleTreeRecorded>
  {
    public global::System.Collections.Generic.IEnumerable<MerkleTreeRecorded> GetIndexed()
    {
      return new List<MerkleTreeRecorded>
      {
      new MerkleTreeRecorded
      {
        RecorderId = RecorderId
      },
      };
    }

    public MerkleTreeRecorded GetNonIndexed()
    {
      return new MerkleTreeRecorded
      {
        LastLeafIndex = LastLeafIndex,
      };
    }
  }

  #endregion
  public static partial class MerkleTreeRecorderContractContainer
  {
    static readonly string __ServiceName = "MTRecorder.MerkleTreeRecorderContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::AElf.Standards.ACS1.MethodFees> __Marshaller_acs1_MethodFees = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Standards.ACS1.MethodFees.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AuthorityInfo> __Marshaller_AuthorityInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AuthorityInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::MTRecorder.Recorder> __Marshaller_MTRecorder_Recorder = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MTRecorder.Recorder.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::MTRecorder.RecordMerkleTreeInput> __Marshaller_MTRecorder_RecordMerkleTreeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MTRecorder.RecordMerkleTreeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::MTRecorder.MerkleProofInput> __Marshaller_MTRecorder_MerkleProofInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MTRecorder.MerkleProofInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::MTRecorder.GetLeafLocatedMerkleTreeInput> __Marshaller_MTRecorder_GetLeafLocatedMerkleTreeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MTRecorder.GetLeafLocatedMerkleTreeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::MTRecorder.GetLeafLocatedMerkleTreeOutput> __Marshaller_MTRecorder_GetLeafLocatedMerkleTreeOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MTRecorder.GetLeafLocatedMerkleTreeOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::MTRecorder.GetMerkleTreeInput> __Marshaller_MTRecorder_GetMerkleTreeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MTRecorder.GetMerkleTreeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::MTRecorder.MerkleTree> __Marshaller_MTRecorder_MerkleTree = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MTRecorder.MerkleTree.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::MTRecorder.RecorderIdInput> __Marshaller_MTRecorder_RecorderIdInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MTRecorder.RecorderIdInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::AElf.Standards.ACS1.MethodFees, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMethodFee = new aelf::Method<global::AElf.Standards.ACS1.MethodFees, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMethodFee",
        __Marshaller_acs1_MethodFees,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeMethodFeeController = new aelf::Method<global::AuthorityInfo, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeMethodFeeController",
        __Marshaller_AuthorityInfo,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Standards.ACS1.MethodFees> __Method_GetMethodFee = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Standards.ACS1.MethodFees>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMethodFee",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_acs1_MethodFees);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AuthorityInfo> __Method_GetMethodFeeController = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AuthorityInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMethodFeeController",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_AuthorityInfo);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::MTRecorder.Recorder, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CreateRecorder = new aelf::Method<global::MTRecorder.Recorder, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "CreateRecorder",
        __Marshaller_MTRecorder_Recorder,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::MTRecorder.RecordMerkleTreeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RecordMerkleTree = new aelf::Method<global::MTRecorder.RecordMerkleTreeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RecordMerkleTree",
        __Marshaller_MTRecorder_RecordMerkleTreeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeOwner = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeOwner",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::MTRecorder.MerkleProofInput, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_MerkleProof = new aelf::Method<global::MTRecorder.MerkleProofInput, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "MerkleProof",
        __Marshaller_MTRecorder_MerkleProofInput,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::MTRecorder.GetLeafLocatedMerkleTreeInput, global::MTRecorder.GetLeafLocatedMerkleTreeOutput> __Method_GetLeafLocatedMerkleTree = new aelf::Method<global::MTRecorder.GetLeafLocatedMerkleTreeInput, global::MTRecorder.GetLeafLocatedMerkleTreeOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLeafLocatedMerkleTree",
        __Marshaller_MTRecorder_GetLeafLocatedMerkleTreeInput,
        __Marshaller_MTRecorder_GetLeafLocatedMerkleTreeOutput);

    static readonly aelf::Method<global::MTRecorder.GetMerkleTreeInput, global::MTRecorder.MerkleTree> __Method_GetMerkleTree = new aelf::Method<global::MTRecorder.GetMerkleTreeInput, global::MTRecorder.MerkleTree>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMerkleTree",
        __Marshaller_MTRecorder_GetMerkleTreeInput,
        __Marshaller_MTRecorder_MerkleTree);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetOwner = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetOwner",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::MTRecorder.RecorderIdInput, global::MTRecorder.Recorder> __Method_GetRecorder = new aelf::Method<global::MTRecorder.RecorderIdInput, global::MTRecorder.Recorder>(
        aelf::MethodType.View,
        __ServiceName,
        "GetRecorder",
        __Marshaller_MTRecorder_RecorderIdInput,
        __Marshaller_MTRecorder_Recorder);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetRecorderCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetRecorderCount",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::MTRecorder.RecorderIdInput, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetLastRecordedLeafIndex = new aelf::Method<global::MTRecorder.RecorderIdInput, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLastRecordedLeafIndex",
        __Marshaller_MTRecorder_RecorderIdInput,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::MTRecorder.RecorderIdInput, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetSatisfiedTreeCount = new aelf::Method<global::MTRecorder.RecorderIdInput, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetSatisfiedTreeCount",
        __Marshaller_MTRecorder_RecorderIdInput,
        __Marshaller_google_protobuf_Int64Value);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MTRecorder.MerkleTreeRecorderReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS1.Acs1Reflection.Descriptor.Services[0],
          global::MTRecorder.MerkleTreeRecorderReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion
  }
}
#endregion

