// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: integer_aggregator_contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.IntegerAggregator {

  #region Events
  public partial class AggregateDataReceived : aelf::IEvent<AggregateDataReceived>
  {
    public global::System.Collections.Generic.IEnumerable<AggregateDataReceived> GetIndexed()
    {
      return new List<AggregateDataReceived>
      {
      };
    }

    public AggregateDataReceived GetNonIndexed()
    {
      return new AggregateDataReceived
      {
        Results = Results,
        FinalResult = FinalResult,
      };
    }
  }

  #endregion
  /// <summary>
  /// StringValue -> StringValue
  /// </summary>
  public static partial class IntegerAggregatorContractContainer
  {
    static readonly string __ServiceName = "IntegerAggregatorContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::AElf.Standards.ACS13.AggregateInput> __Marshaller_acs13_AggregateInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Standards.ACS13.AggregateInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::AElf.Standards.ACS13.AggregateInput, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_Aggregate = new aelf::Method<global::AElf.Standards.ACS13.AggregateInput, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.Action,
        __ServiceName,
        "Aggregate",
        __Marshaller_acs13_AggregateInput,
        __Marshaller_google_protobuf_StringValue);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AElf.Contracts.IntegerAggregator.IntegerAggregatorContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS13.Acs13Reflection.Descriptor.Services[0],
          global::AElf.Contracts.IntegerAggregator.IntegerAggregatorContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion
  }
}
#endregion

