// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: oracle_contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.Oracle {

  #region Events
  public partial class QueryCreated : aelf::IEvent<QueryCreated>
  {
    public global::System.Collections.Generic.IEnumerable<QueryCreated> GetIndexed()
    {
      return new List<QueryCreated>
      {
      };
    }

    public QueryCreated GetNonIndexed()
    {
      return new QueryCreated
      {
        Payment = Payment,
        CallbackInfo = CallbackInfo,
        AggregatorContractAddress = AggregatorContractAddress,
        DesignatedNodeList = DesignatedNodeList,
        QueryInfo = QueryInfo,
        AggregateThreshold = AggregateThreshold,
        QuerySender = QuerySender,
        QueryId = QueryId,
        Token = Token,
        MaximumPermissibleDeviation = MaximumPermissibleDeviation,
      };
    }
  }

  public partial class QueryCancelled : aelf::IEvent<QueryCancelled>
  {
    public global::System.Collections.Generic.IEnumerable<QueryCancelled> GetIndexed()
    {
      return new List<QueryCancelled>
      {
      };
    }

    public QueryCancelled GetNonIndexed()
    {
      return new QueryCancelled
      {
        QueryId = QueryId,
        CancelTime = CancelTime,
      };
    }
  }

  public partial class SufficientCommitmentsCollected : aelf::IEvent<SufficientCommitmentsCollected>
  {
    public global::System.Collections.Generic.IEnumerable<SufficientCommitmentsCollected> GetIndexed()
    {
      return new List<SufficientCommitmentsCollected>
      {
      };
    }

    public SufficientCommitmentsCollected GetNonIndexed()
    {
      return new SufficientCommitmentsCollected
      {
        QueryId = QueryId,
      };
    }
  }

  public partial class Committed : aelf::IEvent<Committed>
  {
    public global::System.Collections.Generic.IEnumerable<Committed> GetIndexed()
    {
      return new List<Committed>
      {
      };
    }

    public Committed GetNonIndexed()
    {
      return new Committed
      {
        QueryId = QueryId,
        OracleNodeAddress = OracleNodeAddress,
        Commitment = Commitment,
      };
    }
  }

  public partial class CommitmentRevealed : aelf::IEvent<CommitmentRevealed>
  {
    public global::System.Collections.Generic.IEnumerable<CommitmentRevealed> GetIndexed()
    {
      return new List<CommitmentRevealed>
      {
      };
    }

    public CommitmentRevealed GetNonIndexed()
    {
      return new CommitmentRevealed
      {
        QueryId = QueryId,
        OracleNodeAddress = OracleNodeAddress,
        Commitment = Commitment,
        Data = Data,
        Salt = Salt,
      };
    }
  }

  public partial class CommitmentRevealFailed : aelf::IEvent<CommitmentRevealFailed>
  {
    public global::System.Collections.Generic.IEnumerable<CommitmentRevealFailed> GetIndexed()
    {
      return new List<CommitmentRevealFailed>
      {
      };
    }

    public CommitmentRevealFailed GetNonIndexed()
    {
      return new CommitmentRevealFailed
      {
        QueryId = QueryId,
        OracleNodeAddress = OracleNodeAddress,
        Commitment = Commitment,
        Data = Data,
        Salt = Salt,
      };
    }
  }

  public partial class QueryCompleted : aelf::IEvent<QueryCompleted>
  {
    public global::System.Collections.Generic.IEnumerable<QueryCompleted> GetIndexed()
    {
      return new List<QueryCompleted>
      {
      };
    }

    public QueryCompleted GetNonIndexed()
    {
      return new QueryCompleted
      {
        QueryId = QueryId,
        Result = Result,
      };
    }
  }

  public partial class TokenLocked : aelf::IEvent<TokenLocked>
  {
    public global::System.Collections.Generic.IEnumerable<TokenLocked> GetIndexed()
    {
      return new List<TokenLocked>
      {
      };
    }

    public TokenLocked GetNonIndexed()
    {
      return new TokenLocked
      {
        OracleNodeAddress = OracleNodeAddress,
        FromAddress = FromAddress,
        LockedAmount = LockedAmount,
      };
    }
  }

  #endregion
  public static partial class OracleContractContainer
  {
    static readonly string __ServiceName = "OracleContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::AElf.Contracts.Oracle.InitializeInput> __Marshaller_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Oracle.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Oracle.QueryInput> __Marshaller_QueryInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Oracle.QueryInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Hash> __Marshaller_aelf_Hash = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Hash.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Oracle.CommitInput> __Marshaller_CommitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Oracle.CommitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Oracle.RevealInput> __Marshaller_RevealInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Oracle.RevealInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Oracle.LockTokensInput> __Marshaller_LockTokensInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Oracle.LockTokensInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Oracle.UnlockTokensInput> __Marshaller_UnlockTokensInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Oracle.UnlockTokensInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Oracle.OracleNodeThreshold> __Marshaller_OracleNodeThreshold = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Oracle.OracleNodeThreshold.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Oracle.QueryRecord> __Marshaller_QueryRecord = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Oracle.QueryRecord.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Oracle.CommitmentMap> __Marshaller_CommitmentMap = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Oracle.CommitmentMap.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.Oracle.AddressList> __Marshaller_AddressList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.Oracle.AddressList.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::AElf.Contracts.Oracle.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::AElf.Contracts.Oracle.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Oracle.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InitializeAndCreateToken = new aelf::Method<global::AElf.Contracts.Oracle.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "InitializeAndCreateToken",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Oracle.QueryInput, global::AElf.Types.Hash> __Method_Query = new aelf::Method<global::AElf.Contracts.Oracle.QueryInput, global::AElf.Types.Hash>(
        aelf::MethodType.Action,
        __ServiceName,
        "Query",
        __Marshaller_QueryInput,
        __Marshaller_aelf_Hash);

    static readonly aelf::Method<global::AElf.Contracts.Oracle.CommitInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Commit = new aelf::Method<global::AElf.Contracts.Oracle.CommitInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Commit",
        __Marshaller_CommitInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Oracle.RevealInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Reveal = new aelf::Method<global::AElf.Contracts.Oracle.RevealInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Reveal",
        __Marshaller_RevealInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CancelQuery = new aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "CancelQuery",
        __Marshaller_aelf_Hash,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeController = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeController",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Oracle.LockTokensInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_LockTokens = new aelf::Method<global::AElf.Contracts.Oracle.LockTokensInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "LockTokens",
        __Marshaller_LockTokensInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Oracle.UnlockTokensInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UnlockTokens = new aelf::Method<global::AElf.Contracts.Oracle.UnlockTokensInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UnlockTokens",
        __Marshaller_UnlockTokensInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.Oracle.OracleNodeThreshold, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetThreshold = new aelf::Method<global::AElf.Contracts.Oracle.OracleNodeThreshold, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetThreshold",
        __Marshaller_OracleNodeThreshold,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeDefaultExpirationSeconds = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeDefaultExpirationSeconds",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_EnableChargeFee = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "EnableChargeFee",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetController = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetController",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.Oracle.QueryRecord> __Method_GetQueryRecord = new aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.Oracle.QueryRecord>(
        aelf::MethodType.View,
        __ServiceName,
        "GetQueryRecord",
        __Marshaller_aelf_Hash,
        __Marshaller_QueryRecord);

    static readonly aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.Oracle.CommitmentMap> __Method_GetCommitmentMap = new aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.Oracle.CommitmentMap>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCommitmentMap",
        __Marshaller_aelf_Hash,
        __Marshaller_CommitmentMap);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_GetOracleTokenSymbol = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetOracleTokenSymbol",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_StringValue);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetLockedTokensAmount = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLockedTokensAmount",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.Oracle.OracleNodeThreshold> __Method_GetThreshold = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Contracts.Oracle.OracleNodeThreshold>(
        aelf::MethodType.View,
        __ServiceName,
        "GetThreshold",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_OracleNodeThreshold);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetDefaultExpirationSeconds = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetDefaultExpirationSeconds",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    static readonly aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.Oracle.AddressList> __Method_GetHelpfulNodeList = new aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.Oracle.AddressList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetHelpfulNodeList",
        __Marshaller_aelf_Hash,
        __Marshaller_AddressList);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AElf.Contracts.Oracle.OracleContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Contracts.Oracle.OracleContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion
  }
}
#endregion

