// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: acs13.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AElf.Standards.ACS13 {

  /// <summary>Holder for reflection information generated from acs13.proto</summary>
  public static partial class Acs13Reflection {

    #region Descriptor
    /// <summary>File descriptor for acs13.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Acs13Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgthY3MxMy5wcm90bxIFYWNzMTMaEmFlbGYvb3B0aW9ucy5wcm90bxoPYWVs",
            "Zi9jb3JlLnByb3RvGh5nb29nbGUvcHJvdG9idWYvd3JhcHBlcnMucHJvdG8i",
            "UAoOQWdncmVnYXRlSW5wdXQSDwoHcmVzdWx0cxgBIAMoCRITCgtmcmVxdWVu",
            "Y2llcxgCIAMoBRIYChBhZ2dyZWdhdGVfb3B0aW9uGAMgASgFMl4KGE9yYWNs",
            "ZUFnZ3JlZ2F0b3JDb250cmFjdBJCCglBZ2dyZWdhdGUSFS5hY3MxMy5BZ2dy",
            "ZWdhdGVJbnB1dBocLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZSIAQiGq",
            "AhRBRWxmLlN0YW5kYXJkcy5BQ1MxM4qS9AEFYWNzMTNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AElf.OptionsReflection.Descriptor, global::AElf.Types.CoreReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Standards.ACS13.AggregateInput), global::AElf.Standards.ACS13.AggregateInput.Parser, new[]{ "Results", "Frequencies", "AggregateOption" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AggregateInput : pb::IMessage<AggregateInput> {
    private static readonly pb::MessageParser<AggregateInput> _parser = new pb::MessageParser<AggregateInput>(() => new AggregateInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AggregateInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Standards.ACS13.Acs13Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AggregateInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AggregateInput(AggregateInput other) : this() {
      results_ = other.results_.Clone();
      frequencies_ = other.frequencies_.Clone();
      aggregateOption_ = other.aggregateOption_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AggregateInput Clone() {
      return new AggregateInput(this);
    }

    /// <summary>Field number for the "results" field.</summary>
    public const int ResultsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_results_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> results_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Results {
      get { return results_; }
    }

    /// <summary>Field number for the "frequencies" field.</summary>
    public const int FrequenciesFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_frequencies_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> frequencies_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Frequencies {
      get { return frequencies_; }
    }

    /// <summary>Field number for the "aggregate_option" field.</summary>
    public const int AggregateOptionFieldNumber = 3;
    private int aggregateOption_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AggregateOption {
      get { return aggregateOption_; }
      set {
        aggregateOption_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AggregateInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AggregateInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!results_.Equals(other.results_)) return false;
      if(!frequencies_.Equals(other.frequencies_)) return false;
      if (AggregateOption != other.AggregateOption) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= results_.GetHashCode();
      hash ^= frequencies_.GetHashCode();
      if (AggregateOption != 0) hash ^= AggregateOption.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      results_.WriteTo(output, _repeated_results_codec);
      frequencies_.WriteTo(output, _repeated_frequencies_codec);
      if (AggregateOption != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AggregateOption);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += results_.CalculateSize(_repeated_results_codec);
      size += frequencies_.CalculateSize(_repeated_frequencies_codec);
      if (AggregateOption != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AggregateOption);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AggregateInput other) {
      if (other == null) {
        return;
      }
      results_.Add(other.results_);
      frequencies_.Add(other.frequencies_);
      if (other.AggregateOption != 0) {
        AggregateOption = other.AggregateOption;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            results_.AddEntriesFrom(input, _repeated_results_codec);
            break;
          }
          case 18:
          case 16: {
            frequencies_.AddEntriesFrom(input, _repeated_frequencies_codec);
            break;
          }
          case 24: {
            AggregateOption = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
