// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: receipt_maker.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AElf.Contracts.ReceiptMakerContract {

  /// <summary>Holder for reflection information generated from receipt_maker.proto</summary>
  public static partial class ReceiptMakerReflection {

    #region Descriptor
    /// <summary>File descriptor for receipt_maker.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReceiptMakerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNyZWNlaXB0X21ha2VyLnByb3RvGg9hZWxmL2NvcmUucHJvdG8aEmFlbGYv",
            "b3B0aW9ucy5wcm90bxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvGh5n",
            "b29nbGUvcHJvdG9idWYvd3JhcHBlcnMucHJvdG8iTAoXR2V0UmVjZWlwdEhh",
            "c2hMaXN0SW5wdXQSGAoQZmlyc3RfbGVhZl9pbmRleBgBIAEoAxIXCg9sYXN0",
            "X2xlYWZfaW5kZXgYAiABKAMiQQoYR2V0UmVjZWlwdEhhc2hMaXN0T3V0cHV0",
            "EiUKEXJlY2VpcHRfaGFzaF9saXN0GAEgAygLMgouYWVsZi5IYXNoMvkBChRS",
            "ZWNlaXB0TWFrZXJDb250cmFjdBJNCg9HZXRSZWNlaXB0Q291bnQSFi5nb29n",
            "bGUucHJvdG9idWYuRW1wdHkaGy5nb29nbGUucHJvdG9idWYuSW50NjRWYWx1",
            "ZSIFiIn3AQESQAoOR2V0UmVjZWlwdEhhc2gSGy5nb29nbGUucHJvdG9idWYu",
            "SW50NjRWYWx1ZRoKLmFlbGYuSGFzaCIFiIn3AQESUAoSR2V0UmVjZWlwdEhh",
            "c2hMaXN0EhguR2V0UmVjZWlwdEhhc2hMaXN0SW5wdXQaGS5HZXRSZWNlaXB0",
            "SGFzaExpc3RPdXRwdXQiBYiJ9wEBQiaqAiNBRWxmLkNvbnRyYWN0cy5SZWNl",
            "aXB0TWFrZXJDb250cmFjdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AElf.Types.CoreReflection.Descriptor, global::AElf.OptionsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.ReceiptMakerContract.GetReceiptHashListInput), global::AElf.Contracts.ReceiptMakerContract.GetReceiptHashListInput.Parser, new[]{ "FirstLeafIndex", "LastLeafIndex" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AElf.Contracts.ReceiptMakerContract.GetReceiptHashListOutput), global::AElf.Contracts.ReceiptMakerContract.GetReceiptHashListOutput.Parser, new[]{ "ReceiptHashList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetReceiptHashListInput : pb::IMessage<GetReceiptHashListInput> {
    private static readonly pb::MessageParser<GetReceiptHashListInput> _parser = new pb::MessageParser<GetReceiptHashListInput>(() => new GetReceiptHashListInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetReceiptHashListInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.ReceiptMakerContract.ReceiptMakerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetReceiptHashListInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetReceiptHashListInput(GetReceiptHashListInput other) : this() {
      firstLeafIndex_ = other.firstLeafIndex_;
      lastLeafIndex_ = other.lastLeafIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetReceiptHashListInput Clone() {
      return new GetReceiptHashListInput(this);
    }

    /// <summary>Field number for the "first_leaf_index" field.</summary>
    public const int FirstLeafIndexFieldNumber = 1;
    private long firstLeafIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long FirstLeafIndex {
      get { return firstLeafIndex_; }
      set {
        firstLeafIndex_ = value;
      }
    }

    /// <summary>Field number for the "last_leaf_index" field.</summary>
    public const int LastLeafIndexFieldNumber = 2;
    private long lastLeafIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long LastLeafIndex {
      get { return lastLeafIndex_; }
      set {
        lastLeafIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetReceiptHashListInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetReceiptHashListInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FirstLeafIndex != other.FirstLeafIndex) return false;
      if (LastLeafIndex != other.LastLeafIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FirstLeafIndex != 0L) hash ^= FirstLeafIndex.GetHashCode();
      if (LastLeafIndex != 0L) hash ^= LastLeafIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FirstLeafIndex != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(FirstLeafIndex);
      }
      if (LastLeafIndex != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LastLeafIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FirstLeafIndex != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FirstLeafIndex);
      }
      if (LastLeafIndex != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LastLeafIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetReceiptHashListInput other) {
      if (other == null) {
        return;
      }
      if (other.FirstLeafIndex != 0L) {
        FirstLeafIndex = other.FirstLeafIndex;
      }
      if (other.LastLeafIndex != 0L) {
        LastLeafIndex = other.LastLeafIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FirstLeafIndex = input.ReadInt64();
            break;
          }
          case 16: {
            LastLeafIndex = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetReceiptHashListOutput : pb::IMessage<GetReceiptHashListOutput> {
    private static readonly pb::MessageParser<GetReceiptHashListOutput> _parser = new pb::MessageParser<GetReceiptHashListOutput>(() => new GetReceiptHashListOutput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetReceiptHashListOutput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AElf.Contracts.ReceiptMakerContract.ReceiptMakerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetReceiptHashListOutput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetReceiptHashListOutput(GetReceiptHashListOutput other) : this() {
      receiptHashList_ = other.receiptHashList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetReceiptHashListOutput Clone() {
      return new GetReceiptHashListOutput(this);
    }

    /// <summary>Field number for the "receipt_hash_list" field.</summary>
    public const int ReceiptHashListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::AElf.Types.Hash> _repeated_receiptHashList_codec
        = pb::FieldCodec.ForMessage(10, global::AElf.Types.Hash.Parser);
    private readonly pbc::RepeatedField<global::AElf.Types.Hash> receiptHashList_ = new pbc::RepeatedField<global::AElf.Types.Hash>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::AElf.Types.Hash> ReceiptHashList {
      get { return receiptHashList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetReceiptHashListOutput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetReceiptHashListOutput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!receiptHashList_.Equals(other.receiptHashList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= receiptHashList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      receiptHashList_.WriteTo(output, _repeated_receiptHashList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += receiptHashList_.CalculateSize(_repeated_receiptHashList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetReceiptHashListOutput other) {
      if (other == null) {
        return;
      }
      receiptHashList_.Add(other.receiptHashList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            receiptHashList_.AddEntriesFrom(input, _repeated_receiptHashList_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
